version: '2'

services:
  api:
    build: .
    container_name: reign_api
    links:
      - db
    ports:
    - "3800:3800"
    volumes:
      - ./api:/opt/api
      - /opt/api/node_modules
  db:
    image: mongo
    container_name: reign_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: